version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
  phpmyadmin:
    image: phpmyadmin
    restart: always 
    ports:
      - 8080:80
    links:
      - "mysql:db"
     
